// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RadarProdutos.Infrastructure.Data;

#nullable disable

namespace RadarProdutos.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RadarProdutos.Domain.Entities.AnalysisConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("MaxMarginPercent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MinMarginPercent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("WeightCompetition")
                        .HasColumnType("numeric");

                    b.Property<decimal>("WeightMargin")
                        .HasColumnType("numeric");

                    b.Property<decimal>("WeightSales")
                        .HasColumnType("numeric");

                    b.Property<decimal>("WeightSentiment")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("AnalysisConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxMarginPercent = 80m,
                            MinMarginPercent = 20m,
                            WeightCompetition = 2.0m,
                            WeightMargin = 3.0m,
                            WeightSales = 2.5m,
                            WeightSentiment = 1.5m
                        });
                });

            modelBuilder.Entity("RadarProdutos.Domain.Entities.MarketplaceConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoUpdateExchangeRate")
                        .HasColumnType("boolean");

                    b.Property<decimal>("CompanyTaxPercent")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DefaultShippingCostUsd")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ImportTaxPercent")
                        .HasColumnType("numeric");

                    b.Property<int>("MaxDeliveryDays")
                        .HasColumnType("integer");

                    b.Property<decimal>("MercadoLivreBoostFee")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MercadoLivreFixedFee")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MercadoLivrePercentFee")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MinMarginPercent")
                        .HasColumnType("numeric");

                    b.Property<int>("MinSalesVolume")
                        .HasColumnType("integer");

                    b.Property<decimal>("MinSupplierRating")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TargetMarginPercent")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("UsdToBrlRate")
                        .HasColumnType("numeric");

                    b.Property<bool>("UseEstimatedShipping")
                        .HasColumnType("boolean");

                    b.Property<decimal>("WeightDelivery")
                        .HasColumnType("numeric");

                    b.Property<decimal>("WeightMargin")
                        .HasColumnType("numeric");

                    b.Property<decimal>("WeightRating")
                        .HasColumnType("numeric");

                    b.Property<decimal>("WeightSales")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("MarketplaceConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AutoUpdateExchangeRate = false,
                            CompanyTaxPercent = 8.93m,
                            CreatedAt = new DateTime(2025, 11, 22, 14, 51, 31, 153, DateTimeKind.Utc).AddTicks(2363),
                            DefaultShippingCostUsd = 15m,
                            ImportTaxPercent = 60m,
                            MaxDeliveryDays = 45,
                            MercadoLivreBoostFee = 5m,
                            MercadoLivreFixedFee = 20m,
                            MercadoLivrePercentFee = 15m,
                            MinMarginPercent = 30m,
                            MinSalesVolume = 100,
                            MinSupplierRating = 4.0m,
                            TargetMarginPercent = 50m,
                            UpdatedAt = new DateTime(2025, 11, 22, 14, 51, 31, 153, DateTimeKind.Utc).AddTicks(2364),
                            UsdToBrlRate = 5.70m,
                            UseEstimatedShipping = true,
                            WeightDelivery = 0.5m,
                            WeightMargin = 1.5m,
                            WeightRating = 1.0m,
                            WeightSales = 1.0m
                        });
                });

            modelBuilder.Entity("RadarProdutos.Domain.Entities.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("HasAdvancedFilters")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasPrioritySupport")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxSearchesPerDay")
                        .HasColumnType("integer");

                    b.Property<int>("MaxSearchesPerMonth")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("PriceMonthly")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Plano gratuito com 10 buscas por mês",
                            HasAdvancedFilters = false,
                            HasPrioritySupport = false,
                            IsActive = true,
                            MaxSearchesPerDay = 3,
                            MaxSearchesPerMonth = 10,
                            Name = "Free",
                            PriceMonthly = 0m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Teste grátis de 7 dias com 30 buscas",
                            HasAdvancedFilters = true,
                            HasPrioritySupport = false,
                            IsActive = true,
                            MaxSearchesPerDay = 10,
                            MaxSearchesPerMonth = 30,
                            Name = "Trial",
                            PriceMonthly = 0m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Plano profissional com buscas ilimitadas",
                            HasAdvancedFilters = true,
                            HasPrioritySupport = true,
                            IsActive = true,
                            MaxSearchesPerDay = -1,
                            MaxSearchesPerMonth = -1,
                            Name = "Pro",
                            PriceMonthly = 47.90m
                        });
                });

            modelBuilder.Entity("RadarProdutos.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompetitionLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EstimatedSalePrice")
                        .HasColumnType("numeric");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<decimal>("MarginPercent")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Orders")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProductAnalysisId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("Sentiment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SupplierPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId");

                    b.HasIndex("ProductAnalysisId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("RadarProdutos.Domain.Entities.ProductAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("Analyses");
                });

            modelBuilder.Entity("RadarProdutos.Domain.Entities.ShippingEstimate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AverageWeight")
                        .HasColumnType("numeric");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxDeliveryDays")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaxWeight")
                        .HasColumnType("numeric");

                    b.Property<int>("MinDeliveryDays")
                        .HasColumnType("integer");

                    b.Property<decimal>("MinWeight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ShippingCostUsd")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("ShippingEstimates");
                });

            modelBuilder.Entity("RadarProdutos.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastResetDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSearchDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<int>("SearchesUsedThisMonth")
                        .HasColumnType("integer");

                    b.Property<int>("SearchesUsedToday")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("UserId", "IsActive");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("RadarProdutos.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RadarProdutos.Domain.Entities.Product", b =>
                {
                    b.HasOne("RadarProdutos.Domain.Entities.ProductAnalysis", "ProductAnalysis")
                        .WithMany("Products")
                        .HasForeignKey("ProductAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ProductAnalysis");
                });

            modelBuilder.Entity("RadarProdutos.Domain.Entities.ProductAnalysis", b =>
                {
                    b.HasOne("RadarProdutos.Domain.Entities.User", "User")
                        .WithMany("Analyses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("RadarProdutos.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("RadarProdutos.Domain.Entities.Plan", "Plan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RadarProdutos.Domain.Entities.User", "User")
                        .WithOne("Subscription")
                        .HasForeignKey("RadarProdutos.Domain.Entities.Subscription", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RadarProdutos.Domain.Entities.Plan", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("RadarProdutos.Domain.Entities.ProductAnalysis", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("RadarProdutos.Domain.Entities.User", b =>
                {
                    b.Navigation("Analyses");

                    b.Navigation("Subscription");
                });
#pragma warning restore 612, 618
        }
    }
}
